version: '3.8'
services:
  api:
    hostname: random-api
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.9 random_information/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
