apiVersion: 1

datasources:
- name: Prometheus
  orgId: 1
  uid: "RDt9j7P7z"
  type: prometheus
  typeName: "Prometheus"
  typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  access: proxy
  url: http://random-prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  isDefault: true
  jsonData:
     httpMethod: POST
  version: 1
  readOnly: false
